# This is a basic workflow to help you get started with Actions

name: Slurm

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    path: 
      - 'slurm/**'
      - '.github/**'
    branches: [ master ]
  pull_request:
    path: 
      - 'slurm/**'
      - '.github/**'
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y slurm-wlm

      - name: Mock dependencies
        run: |
          sudo touch /usr/bin/nvidia-smi
          sudo chmod +x /usr/bin/nvidia-smi

      - name: Systemd unit files
        shell: bash {0}
        run: |
          # systemd will check if the executables refered by the service files exist
          sudo cp -r slurm/etc/systemd/system /etc/systemd/system
          cd slurm/etc/systemd/system
          #sudo systemd-analyze verify ./multi-user.target.wants/slurmd.service
          shopt -s globstar extglob 
          for file in **/*.service
          do
            file="$(basename $file)"
            # cannot verify .conf drop-in files
            # ignore "multi-user.target: Wants dependency dropin /shine-cluster/slurm/etc/systemd/system/multi-user.target.wants/slurmd.service is not a symlink, ignoring."
            output=$(systemd-analyze verify $(basename "$file") 2>&1| grep "$file" | grep -v -F 'is not a symlink')
            echo "$output"
            if [[ $output ]]; then
              hasError=true
            fi
          done
          test -z $hasError
